[versions]
androidx-hilt-compiler = "1.2.0"
androidx-hilt-work = "1.2.0"
androidx-test-core = "1.6.1"
androidx-test-orchestrator = "1.5.0"
androidx-test-runner = "1.6.1"
compose-bom = "2024.06.00"
constraintlayout-compose = "1.0.1"
core-gradle-plugins = "1.3.1"
coroutines = "1.8.1"
hilt = "2.51.1"
junit = "4.13.2"
kotlin = "1.9.24"
mockk = "1.13.12"
paparazzi = "1.3.4"
proton-core-legacy = "26.0.1"
turbine = "1.1.0"

[libraries]
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt-compiler" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt-work" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
proton-core-legacy-presentation = { group = "me.proton.core", name = "presentation", version.ref = "proton-core-legacy" }
proton-core-legacy-presentation-compose = { group = "me.proton.core", name = "presentation-compose", version.ref = "proton-core-legacy" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
